package web

import (
	"bytes"
	"encoding/json"
	"io/fs"
	"net/http"
	"net/http/httptest"
	"os"
	"path"
	"path/filepath"
	"reflect"
	"regexp"
	"sort"
	"strings"
	"testing"

	"github.com/jollaman999/tunnel-manager/internal/api"
	"github.com/jollaman999/tunnel-manager/internal/models"
	"github.com/jollaman999/tunnel-manager/internal/settings"
	"github.com/labstack/echo/v4"
	"go.uber.org/zap"
)

// newServer returns an echo instance with nothing but the UI on it. No request
// made against it carries a cookie, so every answer it gives is an answer
// given without a session.
func newServer() *echo.Echo {
	e := echo.New()
	RegisterRoutes(e, "test-version")

	return e
}

// get runs a GET against e and hands back what was written. No cookie is ever
// attached: the UI has to be reachable by a client that has not logged in.
func get(e *echo.Echo, target string) *httptest.ResponseRecorder {
	req := httptest.NewRequest(http.MethodGet, target, nil)
	rec := httptest.NewRecorder()

	e.ServeHTTP(rec, req)

	return rec
}

// TestEmbeddedFilesArePresent lists what the binary carries. The routes below
// are only worth testing if the files they serve went into the embed in the
// first place, and a file that was renamed but not re-listed fails here rather
// than as a 404 somewhere else.
func TestEmbeddedFilesArePresent(t *testing.T) {
	var names []string

	err := fs.WalkDir(staticFS, ".", func(name string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}

		if !entry.IsDir() {
			names = append(names, name)
		}

		return nil
	})
	if err != nil {
		t.Fatalf("failed to walk the embedded files: %v", err)
	}

	sort.Strings(names)
	t.Logf("embedded files: %v", names)

	want := []string{
		"static/app.js", "static/index.html", "static/screens.js", "static/style.css",
		// The OpenAPI description of /api/**, generated by `make openapi` and
		// committed. It travels in the binary so that a running server can
		// hand it out, which is what the Swagger UI under /ui/api-docs/ reads
		// and what docs/reference.md sends a client to.
		"static/" + specFile,
		// The documentation page and its configuration, written here, and the
		// copy of Swagger UI they load, fetched by `make swagger-ui` and
		// committed beside the licence it is under. They are in the binary for
		// the same reason the screens are: a host that reaches nothing but
		// this server still has to be able to read its own API.
		"static/" + apiDocsDir + "/" + apiDocsIndex,
		"static/" + apiDocsDir + "/init.js",
		"static/" + apiDocsDir + "/LICENSE",
		"static/" + apiDocsDir + "/swagger-ui-bundle.js",
		"static/" + apiDocsDir + "/swagger-ui.css",
		"static/icons/apple-touch-icon.png", "static/icons/favicon-32.png",
		"static/icons/favicon.ico", "static/icons/icon-192.png", "static/icons/icon-512.png",
		"static/icons/logo.svg",
	}
	for _, code := range catalogCodes {
		want = append(want, "static/lang/"+code+".json")
	}

	sort.Strings(want)

	if strings.Join(names, " ") != strings.Join(want, " ") {
		t.Fatalf("embedded files = %v, want %v", names, want)
	}
}

// TestRootRedirectsToTheUI covers the one path that sends a client to /ui/.
// The only other path outside /ui/ is the icon, which TestTheRootIconIsTheUIIcon
// covers.
func TestRootRedirectsToTheUI(t *testing.T) {
	rec := get(newServer(), "/")

	if rec.Code != http.StatusFound {
		t.Fatalf("GET / = %d, want %d", rec.Code, http.StatusFound)
	}

	if location := rec.Header().Get(echo.HeaderLocation); location != uiPrefix {
		t.Fatalf("GET / Location = %q, want %q", location, uiPrefix)
	}
}

// TestTheRootIconIsTheUIIcon covers the one file served outside /ui/. A
// browser, a bookmark and an API client look for /favicon.ico at the root
// without reading any link, so it has to be there, and it has to be the same
// bytes as the icon the page links to rather than a second copy to keep in step.
func TestTheRootIconIsTheUIIcon(t *testing.T) {
	e := newServer()

	rec := get(e, rootIconPath)
	if rec.Code != http.StatusOK {
		t.Fatalf("GET %s = %d, want %d", rootIconPath, rec.Code, http.StatusOK)
	}

	if contentType := rec.Header().Get(echo.HeaderContentType); contentType != "image/x-icon" {
		t.Fatalf("GET %s Content-Type = %q, want %q", rootIconPath, contentType, "image/x-icon")
	}

	linked := get(e, "/ui/icons/favicon.ico")
	if linked.Code != http.StatusOK {
		t.Fatalf("GET /ui/icons/favicon.ico = %d, want %d", linked.Code, http.StatusOK)
	}

	if rec.Body.Len() == 0 || !bytes.Equal(rec.Body.Bytes(), linked.Body.Bytes()) {
		t.Fatalf("GET %s served %d bytes that are not the %d of /ui/icons/favicon.ico",
			rootIconPath, rec.Body.Len(), linked.Body.Len())
	}

	if got, want := rec.Header().Get("ETag"), linked.Header().Get("ETag"); got != want {
		t.Fatalf("GET %s ETag = %q, /ui/icons/favicon.ico carries %q", rootIconPath, got, want)
	}
}

// TestTheRootServesNothingElse keeps the icon from being the start of a second
// UI directory at the root. Every other path there is left to echo, which
// answers it as not found.
func TestTheRootServesNothingElse(t *testing.T) {
	e := newServer()

	for _, target := range []string{"/robots.txt", "/foo", "/favicon.png", "/icons/favicon.ico", "/index.html"} {
		if rec := get(e, target); rec.Code != http.StatusNotFound {
			t.Fatalf("GET %s = %d, want %d", target, rec.Code, http.StatusNotFound)
		}
	}
}

// TestUIWithoutTrailingSlashRedirects keeps /ui from being the one spelling of
// the UI that comes back empty handed.
func TestUIWithoutTrailingSlashRedirects(t *testing.T) {
	rec := get(newServer(), "/ui")

	if rec.Code != http.StatusFound {
		t.Fatalf("GET /ui = %d, want %d", rec.Code, http.StatusFound)
	}

	if location := rec.Header().Get(echo.HeaderLocation); location != uiPrefix {
		t.Fatalf("GET /ui Location = %q, want %q", location, uiPrefix)
	}
}

// TestUIRootServesTheIndex checks the page itself, by a marker that is in the
// file and nowhere else.
func TestUIRootServesTheIndex(t *testing.T) {
	rec := get(newServer(), uiPrefix)

	if rec.Code != http.StatusOK {
		t.Fatalf("GET %s = %d, want %d", uiPrefix, rec.Code, http.StatusOK)
	}

	if !strings.Contains(rec.Body.String(), "<title>Tunnel Manager</title>") {
		t.Fatalf("GET %s did not serve the index page: %q", uiPrefix, rec.Body.String())
	}

	if contentType := rec.Header().Get(echo.HeaderContentType); !strings.HasPrefix(contentType, "text/html") {
		t.Fatalf("GET %s Content-Type = %q, want text/html", uiPrefix, contentType)
	}
}

// TestAssetsAreServedWithTheirType covers the two files the page pulls in. The
// type matters on its own: a stylesheet served as something else is ignored by
// the browser and a script served as something else is refused outright.
func TestAssetsAreServedWithTheirType(t *testing.T) {
	cases := []struct {
		target      string
		contentType string
	}{
		{target: "/ui/app.js", contentType: "text/javascript"},
		{target: "/ui/screens.js", contentType: "text/javascript"},
		{target: "/ui/style.css", contentType: "text/css"},
		{target: "/ui/lang/en.json", contentType: "application/json"},
		{target: "/ui/lang/pt-BR.json", contentType: "application/json"},
		{target: "/ui/icons/favicon-32.png", contentType: "image/png"},
		{target: "/ui/icons/apple-touch-icon.png", contentType: "image/png"},
		{target: "/ui/icons/icon-512.png", contentType: "image/png"},
		{target: "/ui/icons/favicon.ico", contentType: "image/x-icon"},
		{target: "/ui/icons/logo.svg", contentType: "image/svg+xml"},
	}

	e := newServer()

	for _, tc := range cases {
		rec := get(e, tc.target)

		if rec.Code != http.StatusOK {
			t.Fatalf("GET %s = %d, want %d", tc.target, rec.Code, http.StatusOK)
		}

		if rec.Body.Len() == 0 {
			t.Fatalf("GET %s served an empty body", tc.target)
		}

		contentType := rec.Header().Get(echo.HeaderContentType)
		if !strings.HasPrefix(contentType, tc.contentType) {
			t.Fatalf("GET %s Content-Type = %q, want %s", tc.target, contentType, tc.contentType)
		}
	}
}

// TestUnknownPathServesTheIndex is what makes a reload of a screen work once
// the UI routes on the URL.
func TestUnknownPathServesTheIndex(t *testing.T) {
	e := newServer()

	index := get(e, uiPrefix)
	rec := get(e, "/ui/hosts")

	if rec.Code != http.StatusOK {
		t.Fatalf("GET /ui/hosts = %d, want %d", rec.Code, http.StatusOK)
	}

	if rec.Body.String() != index.Body.String() {
		t.Fatalf("GET /ui/hosts did not serve the same body as %s", uiPrefix)
	}
}

// TestEveryScreenPathServesTheIndex walks the paths the UI navigates to. They
// have no route of their own, so a reload or a bookmark of any of them has to
// come back as the page that reads the path and draws the screen.
func TestEveryScreenPathServesTheIndex(t *testing.T) {
	e := newServer()

	index := get(e, uiPrefix)

	for _, target := range []string{"/ui/login", "/ui/setup", "/ui/hosts", "/ui/service-ports",
		"/ui/logs", "/ui/settings", "/ui/uninstalled"} {
		rec := get(e, target)

		if rec.Code != http.StatusOK {
			t.Fatalf("GET %s = %d, want %d", target, rec.Code, http.StatusOK)
		}

		if rec.Body.String() != index.Body.String() {
			t.Fatalf("GET %s did not serve the same body as %s", target, uiPrefix)
		}
	}
}

// TestThePageNamesItsAssetsAbsolutely pins what makes the screens above work.
// The same HTML is served at /ui/hosts as at /ui/, so a src or href without a
// leading slash would be resolved against the screen path and asked for as
// /ui/hosts/app.js, which is not where the file is.
func TestThePageNamesItsAssetsAbsolutely(t *testing.T) {
	reference := regexp.MustCompile(`(?:src|href)="([^"]+)"`)

	page, err := fs.ReadFile(staticFS, "static/"+indexFile)
	if err != nil {
		t.Fatalf("failed to read the page: %v", err)
	}

	matches := reference.FindAllStringSubmatch(string(page), -1)
	if len(matches) == 0 {
		t.Fatalf("the page pulls in nothing, so the assets are not reachable at all")
	}

	e := newServer()

	for _, match := range matches {
		target := match[1]

		if !strings.HasPrefix(target, uiPrefix) {
			t.Fatalf("the page pulls in %q, which is not under %s", target, uiPrefix)
		}

		if rec := get(e, target); rec.Code != http.StatusOK {
			t.Fatalf("GET %s = %d, want %d", target, rec.Code, http.StatusOK)
		}
	}
}

// vendoredDocsAsset says whether a name is part of the copy of Swagger UI that
// `make swagger-ui` fetches, as opposed to the two files written here that sit
// beside it.
//
// The tests below read the bytes of every embedded file looking for something
// that should not be there. That works on files written here and says little
// about a minified bundle of somebody else's code, which holds the words those
// searches look for inside strings it never uses as such. What stands behind
// the vendored files instead is the pinned version in the Makefile and the
// hash checked before the tarball is unpacked.
func vendoredDocsAsset(name string) bool {
	if path.Dir(name) != path.Join(staticRoot, apiDocsDir) {
		return false
	}

	switch path.Base(name) {
	case apiDocsIndex, "init.js":
		return false
	default:
		return true
	}
}

// TestNothingIsFetchedFromTheNetwork keeps the UI working on a host that
// reaches this server and nothing else. A script or a stylesheet pulled from
// somewhere else would leave the screens blank there, and it would hand a third
// party the page the SSH passwords are typed into.
const svgNamespace = "http://www.w3.org/2000/svg"

func TestNothingIsFetchedFromTheNetwork(t *testing.T) {
	external := regexp.MustCompile(`(?i)(https?:)?//[a-z0-9.-]+\.[a-z]{2,}`)

	err := fs.WalkDir(staticFS, ".", func(name string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}

		if entry.IsDir() {
			return nil
		}

		// What holds the documentation page to this origin is the policy it is
		// served under, whose connect-src is 'self', and that is tested in
		// package main. The two files written here are still read.
		if vendoredDocsAsset(name) {
			return nil
		}

		body, err := fs.ReadFile(staticFS, name)
		if err != nil {
			return err
		}

		// The SVG namespace is the one address that is not one. It is the name
		// the drawing on the manual is made under, handed to createElementNS,
		// and nothing is ever fetched from it.
		body = bytes.ReplaceAll(body, []byte(svgNamespace), nil)

		if match := external.Find(body); match != nil {
			t.Errorf("%s names something outside this server: %q", name, match)
		}

		return nil
	})
	if err != nil {
		t.Fatalf("failed to read the embedded files: %v", err)
	}
}

// TestMissingFileWithAnExtensionIsNotFound keeps a mistyped asset name from
// being answered with the page. A 200 full of HTML where a script was asked
// for hides the name that was wrong.
func TestMissingFileWithAnExtensionIsNotFound(t *testing.T) {
	for _, target := range []string{"/ui/nope.js", "/ui/nope.css", "/ui/sub/nope.html"} {
		rec := get(newServer(), target)

		if rec.Code != http.StatusNotFound {
			t.Fatalf("GET %s = %d, want %d", target, rec.Code, http.StatusNotFound)
		}
	}
}

// TestWalkingUpStaysInsideTheEmbeddedTree checks that a path that climbs out of
// /ui/ names nothing outside it. Such a path has no extension after cleaning in
// the case below, so it lands on the page rather than on a file.
func TestWalkingUpStaysInsideTheEmbeddedTree(t *testing.T) {
	rec := get(newServer(), "/ui/../../etc/passwd")

	if rec.Code == http.StatusOK && strings.Contains(rec.Body.String(), "root:") {
		t.Fatalf("GET /ui/../../etc/passwd served something from outside the embedded tree")
	}
}

// TestTheAPIStaysBehindTheSession is the other half of serving the UI without
// one. The UI group being open must not open anything else, so the same server
// carries both and the API path is asked for without a cookie.
func TestTheAPIStaysBehindTheSession(t *testing.T) {
	e := echo.New()
	RegisterRoutes(e, "test-version")

	// The handler is never reached and the session lookup fails before the
	// account is read, so this needs no database.
	authHandler := api.NewAuthHandler(nil, zap.NewNop(), "")

	g := e.Group("/api")
	g.Use(authHandler.RequireSession())
	g.GET("/host", func(c echo.Context) error {
		return c.NoContent(http.StatusOK)
	})

	for _, target := range []string{uiPrefix, rootIconPath} {
		if rec := get(e, target); rec.Code != http.StatusOK {
			t.Fatalf("GET %s = %d, want %d", target, rec.Code, http.StatusOK)
		}
	}

	rec := get(e, "/api/host")
	if rec.Code != http.StatusUnauthorized {
		t.Fatalf("GET /api/host = %d, want %d", rec.Code, http.StatusUnauthorized)
	}
}

// TestTheStaticFilesCarryNoSecret reads everything that is embedded and looks
// for a credential written into it. These files are handed to anyone who asks,
// session or not, so a secret placed in one of them is a published secret.
//
// What is looked for is a value, not a word: a login form has to say
// "password" and a request has to name the field, and neither of those is a
// secret. A quoted literal sitting behind such a name is.
func TestTheStaticFilesCarryNoSecret(t *testing.T) {
	credentialLiteral := regexp.MustCompile("(?i)(password|passwd|secret|token|api[_-]?key|private[_-]?key)[\"'`]?\\s*[:=]+\\s*[\"'`][^\"'`]+[\"'`]")
	pemHeader := regexp.MustCompile(`-----BEGIN [A-Z ]*PRIVATE KEY-----`)

	err := fs.WalkDir(staticFS, ".", func(name string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}

		if entry.IsDir() {
			return nil
		}

		body, err := fs.ReadFile(staticFS, name)
		if err != nil {
			return err
		}

		// The literal search is a heuristic over what somebody wrote, and it
		// is run over what was written here. The copy of Swagger UI describes
		// the password flow of OAuth and the type of a password field, so it
		// holds that word beside a quoted value without either being a secret.
		if !vendoredDocsAsset(name) {
			if match := credentialLiteral.Find(body); match != nil {
				t.Errorf("%s holds what looks like a credential: %q", name, match)
			}
		}

		// The search for a private key is run over everything, vendored or
		// not. It matches the header of a PEM block and nothing else, so there
		// is no reading of it that a bundle of code produces by accident.

		if match := pemHeader.Find(body); match != nil {
			t.Errorf("%s holds a private key: %q", name, match)
		}

		return nil
	})
	if err != nil {
		t.Fatalf("failed to read the embedded files: %v", err)
	}
}

// TestAssetsCarryATagAndAskToBeChecked pins down that a built-in file goes out
// with an entity tag and with a header asking that the tag be checked.
//
// Neither was there. The answer carried a content type and nothing else, which
// leaves a browser to decide for itself how long the file stays good, and what
// it decides is its own business. A phone went on running the scripts of an
// earlier release after a deployment, so a fix that was measured on the server
// had no effect on the screen and looked like a fix that did not work.
func TestAssetsCarryATagAndAskToBeChecked(t *testing.T) {
	e := newServer()

	for _, name := range []string{"/ui/app.js", "/ui/screens.js", "/ui/style.css", "/ui/", rootIconPath} {
		t.Run(name, func(t *testing.T) {
			rec := get(e, name)
			if rec.Code != http.StatusOK {
				t.Fatalf("status = %d, want %d", rec.Code, http.StatusOK)
			}

			tag := rec.Header().Get("ETag")
			if tag == "" {
				t.Fatal("the answer carries no ETag, so a browser has nothing to ask about")
			}
			if cache := rec.Header().Get("Cache-Control"); cache != "no-cache" {
				t.Fatalf("Cache-Control is %q, want %q", cache, "no-cache")
			}

			// The same file asked for again with the tag it was given is a file
			// the browser already holds.
			req := httptest.NewRequest(http.MethodGet, name, nil)
			req.Header.Set("If-None-Match", tag)

			again := httptest.NewRecorder()
			e.ServeHTTP(again, req)

			if again.Code != http.StatusNotModified {
				t.Fatalf("asking again with the tag answered %d, want %d",
					again.Code, http.StatusNotModified)
			}
			if again.Body.Len() != 0 {
				t.Fatalf("the answer that says nothing changed carried %d bytes of body",
					again.Body.Len())
			}
		})
	}
}

// TestTwoAssetsDoNotShareATag is what makes the tag worth having. A tag that is
// the same for every file would have every file answered as unchanged once any
// one of them had been fetched.
func TestTwoAssetsDoNotShareATag(t *testing.T) {
	e := newServer()

	seen := map[string]string{}

	for _, name := range []string{"/ui/app.js", "/ui/screens.js", "/ui/style.css"} {
		tag := get(e, name).Header().Get("ETag")

		if was, ok := seen[tag]; ok {
			t.Fatalf("%s carries the tag of %s", name, was)
		}

		seen[tag] = name
	}
}

// catalogCodes is the thirteen languages the UI is drawn in, in the order
// app.js lists them. It is written out here rather than read from app.js so
// that the tests below have something to compare that file against: a list
// taken from the file it is checking would agree with it whatever it said.
var catalogCodes = []string{"en", "ko", "ja", "zh", "es", "fr", "de", "pt-BR", "ru", "ar", "hi", "vi", "th"}

// baseCatalog is the language every other one falls back to, key by key. It has
// to be complete, and the tests below are what hold it to that.
const baseCatalog = "en"

// catalogKey is the shape a key has to have: an area, at least one part naming
// the thing, and a role at the end saying what kind of string it is.
//
// The role is a closed list on purpose. Eight hundred keys written by six
// different pieces of work will only stay findable if "the word on a button"
// is always spelled the same way, and a name that has to end in one of
// thirteen words cannot drift into ".btn" in one file and ".buttonText" in
// another.
//
// An underscore is allowed inside a part for the keys that are not written by
// hand. The sentence of a refusal and the sentence of a log line are looked up
// under the name the server raises them by, and those names are snake_case; a
// key that respelled them would be a second name for the same thing, and the
// two lists could no longer be held against each other by anything but eye.
var catalogKey = regexp.MustCompile(
	`^[a-z][a-z0-9]*(?:[-_][a-z0-9]+)*(?:\.[a-z][a-z0-9]*(?:[-_][a-z0-9]+)*)+` +
		`\.(?:title|label|hint|button|link|column|option|empty|notice|confirm|error|aria|text)$`)

// readCatalog reads one language file and hands back what is in it. A catalog
// is flat, so an entry that is not a string is a file that has been edited into
// a shape the UI cannot read, and that is reported here rather than as a blank
// on a screen.
func readCatalog(t *testing.T, code string) map[string]string {
	t.Helper()

	body, err := fs.ReadFile(staticFS, "static/lang/"+code+".json")
	if err != nil {
		t.Fatalf("failed to read the %s catalog: %v", code, err)
	}

	var raw map[string]json.RawMessage
	if err := json.Unmarshal(body, &raw); err != nil {
		t.Fatalf("the %s catalog is not a flat object: %v", code, err)
	}

	table := make(map[string]string, len(raw))

	for key, value := range raw {
		var text string
		if err := json.Unmarshal(value, &text); err != nil {
			t.Fatalf("%s catalog: %q is not a string but %s", code, key, value)
		}

		table[key] = text
	}

	return table
}

// readStatic reads one UI file as text.
func readStatic(t *testing.T, name string) string {
	t.Helper()

	body, err := fs.ReadFile(staticFS, "static/"+name)
	if err != nil {
		t.Fatalf("failed to read %s: %v", name, err)
	}

	return string(body)
}

// TestEveryLanguageHasACatalog is what makes the list in the corner of the
// screen true. A code that is offered with no file behind it is a pick that
// draws the page in English and says it is in something else.
func TestEveryLanguageHasACatalog(t *testing.T) {
	e := newServer()

	for _, code := range catalogCodes {
		target := "/ui/lang/" + code + ".json"

		rec := get(e, target)
		if rec.Code != http.StatusOK {
			t.Fatalf("GET %s = %d, want %d", target, rec.Code, http.StatusOK)
		}

		if len(readCatalog(t, code)) == 0 {
			t.Fatalf("the %s catalog holds nothing", code)
		}
	}
}

// TestThePageAndTheScriptAgreeOnTheLanguages compares the two lists of codes.
//
// index.html settles the language in the head, before app.js has been fetched,
// so it holds the list a second time. That is the one duplication this
// arrangement costs, and this is what keeps it from costing anything: a
// language added to one file and not the other fails here instead of being a
// code the page picks and the script has never heard of.
func TestThePageAndTheScriptAgreeOnTheLanguages(t *testing.T) {
	page := readStatic(t, indexFile)
	script := readStatic(t, "app.js")

	// The page: var codes = [...] and var rightToLeft = [...].
	pageList := func(name string) []string {
		found := regexp.MustCompile(`var ` + name + ` = \[([^\]]*)\]`).FindStringSubmatch(page)
		if found == nil {
			t.Fatalf("%s names no %s", indexFile, name)
		}

		return regexp.MustCompile(`"([^"]+)"`).FindAllString(found[1], -1)
	}

	// The script: one line per language, each carrying its code and whether it
	// is written right to left.
	entries := regexp.MustCompile(`\{ code: "([^"]+)", name: "[^"]*", rtl: (true|false) \}`).
		FindAllStringSubmatch(script, -1)
	if len(entries) == 0 {
		t.Fatalf("app.js lists no languages in the shape this test reads")
	}

	var codes, rightToLeft []string

	for _, entry := range entries {
		codes = append(codes, `"`+entry[1]+`"`)

		if entry[2] == "true" {
			rightToLeft = append(rightToLeft, `"`+entry[1]+`"`)
		}
	}

	t.Logf("app.js codes: %v", codes)
	t.Logf("app.js right to left: %v", rightToLeft)

	if got, want := strings.Join(pageList("codes"), " "), strings.Join(codes, " "); got != want {
		t.Fatalf("%s codes = %s, app.js = %s", indexFile, got, want)
	}

	if got, want := strings.Join(pageList("rightToLeft"), " "), strings.Join(rightToLeft, " "); got != want {
		t.Fatalf("%s right to left = %s, app.js = %s", indexFile, got, want)
	}

	// And both of them against what this file says the languages are, so that a
	// language dropped from both at once is still caught.
	var want []string
	for _, code := range catalogCodes {
		want = append(want, `"`+code+`"`)
	}

	if got := strings.Join(codes, " "); got != strings.Join(want, " ") {
		t.Fatalf("app.js codes = %s, want %s", got, strings.Join(want, " "))
	}
}

// TestCatalogKeysFollowTheNamingRule holds every catalog to one way of naming a
// string. There are eight hundred of them to come, written by several separate
// pieces of work, and a key that cannot be guessed at from what it names is a
// key that gets written a second time under another name.
func TestCatalogKeysFollowTheNamingRule(t *testing.T) {
	for _, code := range catalogCodes {
		for key := range readCatalog(t, code) {
			if !catalogKey.MatchString(key) {
				t.Errorf("%s catalog: %q does not read as <area>.<thing>.<role>", code, key)
			}
		}
	}
}

// TestEveryCatalogFallsBackToEnglish is the other half of the fallback. A key
// the chosen language is missing is drawn in English, which only works while
// English is the one catalog that is never missing anything: a key in a
// translation that English has never heard of is a typo, and it would be drawn
// as the name of the key.
//
// A part of a one/many pair that English has not written, a -few next to a
// pair it has, is the one key a translation may hold on its own. It is read
// through plural, which falls back to the many key of the pair where the part
// is missing, so there is an English sentence under it all the same.
func TestEveryCatalogFallsBackToEnglish(t *testing.T) {
	base := readCatalog(t, baseCatalog)
	variants := pluralKeys(scriptKeys(t))

	for _, code := range catalogCodes {
		if code == baseCatalog {
			continue
		}

		for key := range readCatalog(t, code) {
			if _, ok := base[key]; !ok && !variants[key] {
				t.Errorf("%s catalog: %q is in no English catalog to fall back to", code, key)
			}
		}
	}
}

// TestEveryKeyTheUIAsksForIsInEnglish is what keeps the name of a key off the
// screen. t hands back the key it was given where neither catalog has it, which
// is on purpose and is meant never to happen: this is what makes sure of it,
// for every t("...") in the scripts.
func TestEveryKeyTheUIAsksForIsInEnglish(t *testing.T) {
	base := readCatalog(t, baseCatalog)
	asked := regexp.MustCompile(`\bt\("([^"]+)"`)

	var seen int

	for _, name := range []string{"app.js", "screens.js"} {
		for _, use := range asked.FindAllStringSubmatch(readStatic(t, name), -1) {
			seen++

			if _, ok := base[use[1]]; !ok {
				t.Errorf("%s asks for %q, which the English catalog has not got", name, use[1])
			}
		}
	}

	t.Logf("keys asked for in the scripts: %d", seen)

	if seen == 0 {
		t.Fatalf("the scripts ask for no key at all, so this test checks nothing")
	}
}

// TestCatalogValuesCarryNoMarkup keeps a translation from being a way into the
// page. Every value is put on screen with textContent, so a pointed bracket in
// one would be drawn as a pointed bracket; this is the belt to that brace, and
// it also catches a translator who was handed a string with a tag in it and
// translated around the tag.
func TestCatalogValuesCarryNoMarkup(t *testing.T) {
	for _, code := range catalogCodes {
		for key, value := range readCatalog(t, code) {
			if strings.ContainsAny(value, "<>") {
				t.Errorf("%s catalog: %q carries markup: %q", code, key, value)
			}
		}
	}
}

// TestCatalogValuesCarryNoDirectionMarks keeps the laying out of a sentence in
// one place. app.js writes every value it fills in between FIRST STRONG ISOLATE
// and POP DIRECTIONAL ISOLATE, which is what keeps the slash of a path from
// being carried to the far end of a sentence on a page that reads right to
// left; a translator who reached for a mark of their own would be working
// against that, and the marks are drawn as nothing, so nobody reviewing the
// file would see them.
//
// Every character the standard calls an explicit formatting character is
// listed, the overrides and embeddings as well as the isolates, along with the
// three implicit marks. None of them belongs in a value: the run they would
// wrap is not in the value, it is the value.
func TestCatalogValuesCarryNoDirectionMarks(t *testing.T) {
	marks := map[rune]string{
		'\u200e': "LEFT-TO-RIGHT MARK",
		'\u200f': "RIGHT-TO-LEFT MARK",
		'\u061c': "ARABIC LETTER MARK",
		'\u202a': "LEFT-TO-RIGHT EMBEDDING",
		'\u202b': "RIGHT-TO-LEFT EMBEDDING",
		'\u202c': "POP DIRECTIONAL FORMATTING",
		'\u202d': "LEFT-TO-RIGHT OVERRIDE",
		'\u202e': "RIGHT-TO-LEFT OVERRIDE",
		'\u2066': "LEFT-TO-RIGHT ISOLATE",
		'\u2067': "RIGHT-TO-LEFT ISOLATE",
		'\u2068': "FIRST STRONG ISOLATE",
		'\u2069': "POP DIRECTIONAL ISOLATE",
	}

	for _, code := range catalogCodes {
		for key, value := range readCatalog(t, code) {
			for _, found := range value {
				name, marked := marks[found]
				if marked {
					t.Errorf("%s catalog: %q carries %s (U+%04X), which app.js and not the catalog puts round a value", code, key, name, found)
				}
			}
		}
	}
}

// TestPlaceholdersAreNamedAndKnown holds the fill-ins of a translation to the
// ones the English string has.
//
// They are named and not numbered so that a language may put them in another
// order, which is the whole reason for naming them; the cost of that freedom is
// that a name can be misspelled, and a misspelled one would be drawn on the
// screen as a word in braces. A translation may leave one out, since not every
// language needs to repeat what is already on the screen, but it may not invent
// one.
func TestPlaceholdersAreNamedAndKnown(t *testing.T) {
	named := regexp.MustCompile(`\{([^}]*)\}`)
	// The underscore is here for the values that are not this UI's to name. A
	// refusal hands its values over under the names the server wrote them
	// under, and a log line is filled in from its own fields, both of which are
	// snake_case; app.js fills in exactly this shape.
	plain := regexp.MustCompile(`^[a-z][a-z0-9_]*$`)
	base := readCatalog(t, baseCatalog)

	namesIn := func(value string) map[string]bool {
		names := map[string]bool{}
		for _, found := range named.FindAllStringSubmatch(value, -1) {
			names[found[1]] = true
		}

		return names
	}

	for _, code := range catalogCodes {
		for key, value := range readCatalog(t, code) {
			english, translated := base[key]

			for name := range namesIn(value) {
				if !plain.MatchString(name) {
					t.Errorf("%s catalog: %q holds {%s}, which is not a name app.js fills in", code, key, name)

					continue
				}

				if code == baseCatalog || !translated {
					continue
				}

				if !namesIn(english)[name] {
					t.Errorf("%s catalog: %q holds {%s}, which the English string has not got", code, key, name)
				}
			}
		}
	}
}

// TestTheServerAndTheUIAgreeOnTheLanguages is the fourth list held against the
// other three. The settings hold a default language for the installation, and
// the value they take has to be a code the UI is actually drawn in: one that is
// stored and has no catalog behind it draws the page in the names of its keys
// for every browser that has picked nothing, and one the UI offers and the
// server refuses is a language an operator can pick and cannot save.
//
// It sits here rather than in internal/settings because this is where the UI
// files are. They are embedded in this package, so this is the one place the
// list the server keeps, the list app.js offers, the list index.html reads
// before app.js is fetched, and the catalog files themselves can all be laid
// side by side. internal/settings knows nothing of where those files live, and
// a list read out of the thing it is checking would agree with it whatever it
// said.
func TestTheServerAndTheUIAgreeOnTheLanguages(t *testing.T) {
	served := settings.Languages()

	t.Logf("the settings take: %v", served)

	// The order is compared too, not only the membership. The UI offers the
	// languages in this order and matches a browser language against them in
	// it, so a list that holds the same codes in another order is two lists
	// that have to be read separately to be understood.
	if got, want := strings.Join(served, " "), strings.Join(catalogCodes, " "); got != want {
		t.Fatalf("the settings take %s, the UI is drawn in %s", got, want)
	}

	// And each of them against the file the words come out of, so that a code
	// added to every list at once and never translated is caught as well.
	for _, code := range served {
		if len(readCatalog(t, code)) == 0 {
			t.Errorf("the settings take %s, which no catalog holds any words for", code)
		}
	}
}

// keyShaped is a string literal in a script that reads as a catalog key. It is
// the same shape catalogKey holds a key to, anchored so that a sentence which
// happens to contain a dotted word is not taken for one.
var keyShaped = regexp.MustCompile(`^[a-z][a-z0-9]*(?:[-_][a-z0-9]+)*(?:\.[a-z][a-z0-9]*(?:[-_][a-z0-9]+)*)+` +
	`\.(?:title|label|hint|button|link|column|option|empty|notice|confirm|error|aria|text)$`)

// scriptKeys is every key the two scripts name, however they name it.
//
// It is not only the t("...") calls. A sentence that reads differently for one
// and for many is two keys picked between before either is looked up, and the
// navigation holds the key of each screen rather than its words, so neither of
// those is inside a t( and neither would be seen by a scan that looked only
// there.
func scriptKeys(t *testing.T) map[string]bool {
	t.Helper()

	literal := regexp.MustCompile(`"([^"\\\n]*)"`)
	keys := map[string]bool{}

	for _, name := range []string{"app.js", "screens.js"} {
		for _, found := range literal.FindAllStringSubmatch(readStatic(t, name), -1) {
			if keyShaped.MatchString(found[1]) {
				keys[found[1]] = true
			}
		}
	}

	return keys
}

// pluralParts is every part a count can fall in, as Intl.PluralRules names
// them. The scripts write out the keys of two of them, one and many, and
// plural in app.js puts the other four together at run time from those two.
var pluralParts = []string{"zero", "one", "two", "few", "many", "other"}

// pluralKeys is every key plural can put together from the pairs the scripts
// name: for each pair that reads P-one-S and P-many-S, the same key with each
// of the six parts written in. None of the four the scripts do not write out
// has to be in a catalog, since plural falls back to many and then to one, but
// a catalog that holds one of them is holding a key that is asked for.
func pluralKeys(keys map[string]bool) map[string]bool {
	out := map[string]bool{}

	for one := range keys {
		for at := strings.Index(one, "-one"); at >= 0; at = next(one, "-one", at) {
			head, tail := one[:at], one[at+len("-one"):]

			if !keys[head+"-many"+tail] {
				continue
			}

			for _, part := range pluralParts {
				out[head+"-"+part+tail] = true
			}
		}
	}

	return out
}

// next is the index of the occurrence of sub in s after at, or -1.
func next(s, sub string, at int) int {
	found := strings.Index(s[at+1:], sub)
	if found < 0 {
		return -1
	}

	return at + 1 + found
}

// TestEveryKeyTheScriptsNameIsInEnglish is the wider half of the check above.
// A key that is picked between before it is looked up would be handed back as
// its own name on the screen, exactly as a missing t("...") key would, and
// nothing else would catch it.
//
// The keys plural puts together are not held to this. Those fall back to a
// key the scripts do write out, so a part no catalog has written is not a
// name on the screen; what has to be in English is the pair itself.
func TestEveryKeyTheScriptsNameIsInEnglish(t *testing.T) {
	base := readCatalog(t, baseCatalog)
	keys := scriptKeys(t)

	t.Logf("keys named in the scripts: %d", len(keys))

	if len(keys) == 0 {
		t.Fatalf("the scripts name no key at all, so this test checks nothing")
	}

	for key := range keys {
		if _, ok := base[key]; !ok {
			t.Errorf("the scripts name %q, which the English catalog has not got", key)
		}
	}

	variants := pluralKeys(keys)

	t.Logf("keys plural can put together from those: %d", len(variants))

	if len(variants) == 0 {
		t.Fatalf("the scripts name no one/many pair at all, so nothing here reads plural's keys")
	}
}

// TestEveryEnglishKeyIsAskedFor is the other direction, and it is what keeps
// the catalog from growing a tail. A key no screen asks for is a string that
// costs thirteen translations and reaches nobody, and it is also what a key
// renamed in the scripts and not in the catalog leaves behind.
//
// The keys the scripts build at run time are counted as asked for. They are the
// sentence of every refusal the server can raise and of every log line it can
// write, and neither is written out in a script: the answer and the log line
// carry the name, and the script puts the key together from it. What holds
// those to something is the list the server keeps, which is where generatedKeys
// reads them from, so a key under one of the two prefixes that stands for no
// code and no identifier is still caught here.
//
// The keys plural puts together from a one/many pair are counted as asked for
// as well. None of them is written out in a script, and none has to be in the
// catalog, but a catalog that holds a -few key next to a pair is holding one
// plural asks for the moment a count falls in that part.
func TestEveryEnglishKeyIsAskedFor(t *testing.T) {
	keys := scriptKeys(t)
	generated := generatedKeys(t)
	variants := pluralKeys(keys)

	for key := range readCatalog(t, baseCatalog) {
		if !keys[key] && !generated[key] && !variants[key] {
			t.Errorf("the English catalog holds %q, which no script asks for", key)
		}
	}
}

// The three kinds of key a script builds rather than writes out. The prefix
// says which of the three a key belongs to, so the four groups the catalog
// holds - the words of the screens, the refusals, the log lines and the strings
// an answer names - can be told apart by name alone, and the role at the end is
// the one the naming rule asks for.
const (
	refusalKeyPrefix = "error."
	refusalKeyRole   = ".error"
	logKeyPrefix     = "log."
	logKeyRole       = ".text"
	answerKeyPrefix  = "answer."
	answerKeyRole    = ".text"
)

// untranslatedLogID is the one log line that has no sentence in the catalog.
// gorm writes the words of it, so what the line says is not this application's
// to name: there is no fixed sentence behind the identifier and nothing for a
// translator to be handed. The Logs screen shows the message out of the file
// for it, which is what it does for every line it has no sentence for.
const untranslatedLogID = "database.gorm_message"

// unnamedRefusalCode is the code a refusal goes out under when the package that
// raised it has no sentence registered for it. It stands for a bug rather than
// for a refusal anybody can word, and the answer carries the code itself as its
// text, so there is nothing to translate and it is left out of the catalog.
const unnamedRefusalCode = "unspecified"

// The three lists the server keeps, read out of the files that hold them.
// They are read as text rather than imported because all of them are
// unexported: what is wanted here is the set of names, and the names are the
// whole of what those declarations are.
//
// The refusals and the log lines are each declared in one file. The strings an
// answer names are declared beside the thing that sends them, one file per
// screen, and what holds them together is their kind, textCode, which is what
// they are read by here.
var (
	refusalCodeDeclaration = regexp.MustCompile(`errorCode = "([a-z0-9_.]+)"`)
	logIDDeclaration       = regexp.MustCompile(`(?m)^\t[A-Za-z]+\s+ID = "([a-z0-9_.]+)"$`)
	textCodeDeclaration    = regexp.MustCompile(`textCode = "([a-z0-9_.]+)"`)
)

// namedIn reads one source file of another package and hands back what the
// pattern names in it.
//
// The path is relative to this package, which is where a test runs. It is the
// server's own list that has to be read: a list written out here a second time
// would be a copy to keep in step, and the thing being checked is exactly that
// the catalog and the server have not drifted apart.
func namedIn(t *testing.T, path string, pattern *regexp.Regexp) []string {
	t.Helper()

	body, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("failed to read %s: %v", path, err)
	}

	found := pattern.FindAllStringSubmatch(string(body), -1)
	if len(found) == 0 {
		t.Fatalf("%s names nothing in the shape this test reads", path)
	}

	names := make([]string, 0, len(found))
	for _, match := range found {
		names = append(names, match[1])
	}

	return names
}

// refusalCodes is every code a refusal is raised under, and logIDs is every
// identifier a log line is written with.
func refusalCodes(t *testing.T) []string {
	t.Helper()

	var codes []string

	for _, code := range namedIn(t, "../api/errors.go", refusalCodeDeclaration) {
		if code == unnamedRefusalCode {
			continue
		}

		codes = append(codes, code)
	}

	return codes
}

func logIDs(t *testing.T) []string {
	t.Helper()

	return namedIn(t, "../logid/logid.go", logIDDeclaration)
}

// textCodes is every code an answer names a string by. The declarations are
// spread over the files of the api package, so every file of it that is not a
// test is read, and a file that declares none is not a fault: most do not.
func textCodes(t *testing.T) []string {
	t.Helper()

	paths, err := filepath.Glob("../api/*.go")
	if err != nil {
		t.Fatalf("failed to list the files of the api package: %v", err)
	}

	var codes []string

	for _, path := range paths {
		if strings.HasSuffix(path, "_test.go") {
			continue
		}

		body, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("failed to read %s: %v", path, err)
		}

		for _, match := range textCodeDeclaration.FindAllStringSubmatch(string(body), -1) {
			codes = append(codes, match[1])
		}
	}

	if len(codes) == 0 {
		t.Fatalf("the api package declares no textCode, so nothing holds the answers to the catalog")
	}

	return codes
}

// generatedKeys is every key a script looks a server string up under.
func generatedKeys(t *testing.T) map[string]bool {
	t.Helper()

	keys := map[string]bool{}

	for _, code := range refusalCodes(t) {
		keys[refusalKeyPrefix+code+refusalKeyRole] = true
	}

	for _, id := range logIDs(t) {
		if id == untranslatedLogID {
			continue
		}

		keys[logKeyPrefix+id+logKeyRole] = true
	}

	for _, code := range textCodes(t) {
		keys[answerKeyPrefix+code+answerKeyRole] = true
	}

	return keys
}

// TestEverySentenceTheServerCanSendIsInEnglish is the half of the two-way check
// that no scan of the scripts can do.
//
// A refusal the catalog has no sentence for is shown as the English sentence
// the answer carries, a log line with no sentence is shown as the English
// message out of the file, and a string an answer names without a sentence
// here is shown as the English beside the name. None is a blank screen, which
// is why this is one test rather than a rule the UI enforces at run time; but
// all three are a screen in one language with a sentence in another, and a
// code added to the server without a sentence here would go unnoticed until
// somebody reading the screen in their own language met an English paragraph
// in the middle of it.
func TestEverySentenceTheServerCanSendIsInEnglish(t *testing.T) {
	base := readCatalog(t, baseCatalog)

	codes := refusalCodes(t)
	ids := logIDs(t)
	named := textCodes(t)

	t.Logf("refusals the server can raise: %d", len(codes))
	t.Logf("identifiers a log line can carry: %d", len(ids))
	t.Logf("strings an answer can name: %d", len(named))

	for _, code := range named {
		key := answerKeyPrefix + code + answerKeyRole

		if _, ok := base[key]; !ok {
			t.Errorf("the server names the string %q, which the English catalog has no %q for",
				code, key)
		}
	}

	for _, code := range codes {
		key := refusalKeyPrefix + code + refusalKeyRole

		if _, ok := base[key]; !ok {
			t.Errorf("the server raises the refusal %q, which the English catalog has no %q for",
				code, key)
		}
	}

	for _, id := range ids {
		if id == untranslatedLogID {
			if _, ok := base[logKeyPrefix+id+logKeyRole]; ok {
				t.Errorf("the English catalog holds a sentence for %q, whose words are not ours to write",
					id)
			}

			continue
		}

		key := logKeyPrefix + id + logKeyRole

		if _, ok := base[key]; !ok {
			t.Errorf("the server writes the log line %q, which the English catalog has no %q for",
				id, key)
		}
	}
}

// scriptRefusalDeclaration is how app.js writes out a code it decides
// something on: a const whose name ends in Code, holding the name the server
// raises the refusal under. Two of them are there, one that moves the operator
// to the setup screen and one that keeps them on the screen they are on, and
// both are a decision taken on a name rather than on a sentence.
var scriptRefusalDeclaration = regexp.MustCompile(`(?m)^const [A-Za-z]+Code = "([a-z0-9_.]+)";$`)

// TestEveryRefusalTheScriptActsOnIsOneTheServerRaises holds the names the UI
// branches on to the list the server raises them from.
//
// A code the server renames and the script does not is the worst shape this can
// fail in, because nothing about it looks broken: the answer still arrives, the
// sentence is still read out of the catalog, and only the branch behind the
// name quietly stops being taken. For the host key password that branch is what
// keeps a wrong password from logging the operator out, so its going missing
// would put the bug it was written for back with no test failing.
func TestEveryRefusalTheScriptActsOnIsOneTheServerRaises(t *testing.T) {
	raised := map[string]bool{}

	for _, code := range refusalCodes(t) {
		raised[code] = true
	}

	found := scriptRefusalDeclaration.FindAllStringSubmatch(readStatic(t, "app.js"), -1)
	if len(found) == 0 {
		t.Fatalf("app.js names no refusal code, so nothing here reads what the UI acts on")
	}

	t.Logf("refusal codes the script acts on: %d", len(found))

	for _, match := range found {
		if !raised[match[1]] {
			t.Errorf("the script acts on the refusal %q, which the server does not raise", match[1])
		}
	}
}

// scriptBindScope is how screens.js writes down one of the two words a bind
// scope can be.
var scriptBindScope = regexp.MustCompile(`(?m)^const (bindScope[A-Za-z]+) = "([^"]*)";$`)

// TestTheScreensNameTheBindScopesTheModelStores holds the words the screens
// send against the words the column takes.
//
// The two are compared rather than written out once, because a word that does
// not match is refused nowhere the operator would see it in time: the list on
// the screen still offers two entries under sentences out of the catalog, and
// what comes back is a refusal of the whole request naming a field. The check
// on the column would be the last thing to speak, and by then the screen has
// been offering a choice it could never store.
func TestTheScreensNameTheBindScopesTheModelStores(t *testing.T) {
	want := map[string]string{
		"bindScopeWildcard": models.BindScopeWildcard,
		"bindScopeLoopback": models.BindScopeLoopback,
	}

	found := map[string]string{}

	for _, said := range scriptBindScope.FindAllStringSubmatch(readStatic(t, "screens.js"), -1) {
		found[said[1]] = said[2]
	}

	if len(found) == 0 {
		t.Fatalf("screens.js names no bind scope in the shape this test reads")
	}

	for name, word := range found {
		stored, known := want[name]
		if !known {
			t.Errorf("screens.js names the bind scope %s, which the model has no word for", name)
			continue
		}

		if word != stored {
			t.Errorf("screens.js sends %s as %q, which the model stores as %q", name, word, stored)
		}
	}

	for name := range want {
		if _, ok := found[name]; !ok {
			t.Errorf("screens.js names no %s, so one of the two scopes cannot be picked", name)
		}
	}
}

// The two shapes a script writes a request body in: the object it builds, and
// the fields it sets on that object afterwards. A field is set afterwards where
// it is only sent sometimes, an empty password box being the first of those, so
// reading the object alone would miss half of what goes out.
var (
	scriptBodyLiteral = regexp.MustCompile(`(?m)^ {4}([a-z][a-z0-9_]*):`)
	scriptBodyField   = regexp.MustCompile(`(?m)^ +body\.([a-z][a-z0-9_]*) =`)
)

// TestTheFieldsTheScreensSendAreOnesTheRequestsCarry holds what the screens put
// in a request body against what the request is bound into.
//
// A name that is in one and not in the other is the quietest failure this UI
// has. Binding leaves a field it does not know about exactly where it found it,
// so the request is answered with a 200, the screen says the Host was stored,
// and the one value the operator went in to change was dropped on the way. It
// is what a field moved from one record to another leaves behind, which is how
// the bind address became a scope on the assignment: the screens went on
// sending it under the old name to a request that had stopped carrying it.
func TestTheFieldsTheScreensSendAreOnesTheRequestsCarry(t *testing.T) {
	script := readStatic(t, "screens.js")

	for _, held := range []struct {
		name string
		into any
	}{
		{"createHost", models.CreateHostRequest{}},
		{"updateHost", models.UpdateHostRequest{}},
		// The update of a service port is bound into the request the create is
		// bound into, so both of the functions that build that body are held to
		// the one struct.
		{"servicePortBody", models.CreateServicePortRequest{}},
		{"createServicePort", models.CreateServicePortRequest{}},
		// The add and the edit of a local forward are bound into one request,
		// and so is the switch of one on or off.
		{"localForwardBody", models.LocalForwardRequest{}},
		{"localForwardFlipBody", models.LocalForwardRequest{}},
	} {
		carried := jsonFields(t, held.into)
		sent := bodyFields(t, script, held.name)

		if len(sent) == 0 {
			t.Errorf("screens.js builds no request body in %s, so nothing here is checked", held.name)
			continue
		}

		t.Logf("%s sends: %s", held.name, strings.Join(sent, " "))

		for _, field := range sent {
			if !carried[field] {
				t.Errorf("screens.js sends %q from %s, which %T does not carry",
					field, held.name, held.into)
			}
		}
	}
}

// bodyFields are the names one function of a script writes into a request body.
// The object it builds is read from the first line that opens one to the line
// that closes it at the indentation a body sits on, and the fields set on it
// afterwards are read over the whole function.
func bodyFields(t *testing.T, script, name string) []string {
	t.Helper()

	at := strings.Index(script, "function "+name+"(")
	if at < 0 {
		t.Fatalf("screens.js has no function named %s", name)
	}

	body := script[at:]
	if end := strings.Index(body, "\n}\n"); end >= 0 {
		body = body[:end]
	}

	var found []string

	opens := strings.Index(body, "const body = {")
	if opens < 0 {
		opens = strings.Index(body, "  return {")
	}

	if opens >= 0 {
		literal := body[opens:]
		if closes := strings.Index(literal, "\n  };"); closes >= 0 {
			literal = literal[:closes]
		}

		for _, said := range scriptBodyLiteral.FindAllStringSubmatch(literal, -1) {
			found = append(found, said[1])
		}
	}

	for _, said := range scriptBodyField.FindAllStringSubmatch(body, -1) {
		found = append(found, said[1])
	}

	sort.Strings(found)

	return found
}

// jsonFields are the names a struct is bound from, out of the tags themselves
// rather than out of a list written beside them: a tag renamed without the list
// being touched is exactly what this is here to catch.
func jsonFields(t *testing.T, of any) map[string]bool {
	t.Helper()

	shape := reflect.TypeOf(of)
	if shape.Kind() != reflect.Struct {
		t.Fatalf("%T is not a struct", of)
	}

	names := map[string]bool{}

	for i := 0; i < shape.NumField(); i++ {
		tag := shape.Field(i).Tag.Get("json")
		if tag == "" || tag == "-" {
			continue
		}

		names[strings.Split(tag, ",")[0]] = true
	}

	return names
}

// addressLineMarker is what the line under a tunnel row that says what is known
// about the addresses of its forwarded port leaves on the element it draws. The
// tests below find that line by it rather than by the name of the function, so
// that renaming the function does not quietly stop them checking anything.
const addressLineMarker = "dataset.openReach"

// claimsNotToBeMade are what the line may not say, in the English catalog,
// which is the one every other catalog is written from.
//
// None of them is measurable from here. The reply to a tcpip-forward request
// carries a port and no address, so what the SSH server bound is never said,
// and an answer to a request is not a binding: a server set to bind every
// interface takes both address families on the first request and turns the
// second one down, for a request that named the loopback address as much as for
// one that named the wildcard. A line that reads an answer as a port that is
// open, or as traffic that will not arrive, is telling an operator something
// this program has not measured and cannot.
var claimsNotToBeMade = []string{
	"refus", "reject", "denied", "turned down",
	"alone", "only", "half of",
	"unreachable", "not reachable", "cannot be reached",
	"does not arrive", "never arrives", "nothing that dials",
	"is open on", "opened on", "not open",
}

// TestTheAddressLineClaimsNothingItCannotMeasure holds the sentences under a
// tunnel row to what was asked, what was answered and what a connection from
// here confirmed.
//
// The words are held rather than the drawing because the words are what an
// operator acts on. A sentence that says the Host turned an address down and
// that nothing reaches it over that family sends them to change a machine that
// may have the port open, and there is nothing on the screen to tell them
// otherwise.
func TestTheAddressLineClaimsNothingItCannotMeasure(t *testing.T) {
	base := readCatalog(t, baseCatalog)
	named := regexp.MustCompile(`\bt\("([^"]+)"`)

	held := map[string]bool{}

	// The keys the line itself names, which is what catches a line drawn from
	// the sentences it used to be drawn from.
	for _, use := range named.FindAllStringSubmatch(
		scriptFunctionCarrying(t, readStatic(t, "screens.js"), addressLineMarker), -1) {
		held[use[1]] = true
	}

	// And the keys of the group it is written in, which is what catches a
	// sentence added to one of the functions it is put together by.
	for key := range base {
		if strings.HasPrefix(key, "status.addresses-") {
			held[key] = true
		}
	}

	t.Logf("sentences the address line is made of: %d", len(held))

	if len(held) == 0 {
		t.Fatalf("no sentence of the address line was found, so this test checks nothing")
	}

	for key := range held {
		value := strings.ToLower(base[key])

		for _, claim := range claimsNotToBeMade {
			if strings.Contains(value, claim) {
				t.Errorf("the English catalog says %q under %q, which is not something this end "+
					"measured: an answer to a forward request is not what the server bound", claim, key)
			}
		}
	}
}

// TestTheAddressLineIsNotDrawnAsAWarning keeps the note under a row a note.
//
// Nothing in it is something to go and fix. A tunnel whose ports were asked for
// on the Host itself has no address this machine can try, which is the scope
// doing what it was picked for, and painted the way a failure is it reads as a
// tunnel with something wrong with it. The one warning about reach on this
// screen is the box drawn for a port that was tried and gave nothing back.
func TestTheAddressLineIsNotDrawnAsAWarning(t *testing.T) {
	const warningClass = "reach-advice"

	body := scriptFunctionCarrying(t, readStatic(t, "screens.js"), addressLineMarker)
	painted := regexp.MustCompile(`className = "([^"]+)"`).FindStringSubmatch(body)

	if painted == nil {
		t.Fatalf("the address line is drawn with no class of its own, so nothing here is checked")
	}

	if painted[1] == warningClass {
		t.Fatalf("the address line is drawn as %q, which is the box a port that did not answer is "+
			"warned about in", painted[1])
	}

	if style := readStatic(t, "style.css"); !strings.Contains(style, "."+painted[1]) {
		t.Fatalf("the address line is drawn as %q, which style.css has no rule for", painted[1])
	}
}

// scriptFunctionCarrying is the body of the function of a script that carries
// the string given, from the line it is declared on to the line that closes it.
// A function is found by something it does rather than by its name, so that a
// test is not answered by a rename.
func scriptFunctionCarrying(t *testing.T, script, carried string) string {
	t.Helper()

	at := strings.Index(script, carried)
	if at < 0 {
		t.Fatalf("no function of the script carries %q", carried)
	}

	opens := strings.LastIndex(script[:at], "\nfunction ")
	if opens < 0 {
		t.Fatalf("%q is not inside a function of the script", carried)
	}

	body := script[opens+1:]
	if closes := strings.Index(body, "\n}\n"); closes >= 0 {
		body = body[:closes]
	}

	return body
}
