package tlsserve

import (
	"crypto/tls"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"strconv"
	"strings"
	"testing"
	"time"

	"go.uber.org/zap"
)

// testPeekTimeout is what the tests run the splitter on. The real one is ten
// seconds, and waiting that out is the whole of the test that covers a client
// which sends nothing.
const testPeekTimeout = 300 * time.Millisecond

// harness is the port as main puts it together: one listener, split in two,
// with the TLS side serving a body and the plaintext side answering with a
// redirect.
type harness struct {
	split  *Splitter
	addr   string
	port   int
	tlsCfg *tls.Config
}

func newHarness(t *testing.T) *harness {
	t.Helper()

	listener, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatalf("failed to listen: %v", err)
	}

	port := listener.Addr().(*net.TCPAddr).Port

	generated, err := generate(time.Now())
	if err != nil {
		t.Fatalf("generate: %v", err)
	}

	keyPair, err := tls.X509KeyPair(generated.certPEM, generated.keyPEM)
	if err != nil {
		t.Fatalf("the generated certificate and key do not form a pair: %v", err)
	}

	split := newSplitter(listener, zap.NewNop(), testPeekTimeout)

	tlsCfg := ServerConfig(&keyPair)

	tlsServer := &http.Server{
		Handler: http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
			_, _ = io.WriteString(w, "served over TLS")
		}),
	}

	go func() {
		_ = tlsServer.Serve(tls.NewListener(split.TLS(), tlsCfg))
	}()

	redirectServer := NewRedirectServer(port, zap.NewNop())

	go func() {
		_ = redirectServer.Serve(split.Plain())
	}()

	t.Cleanup(func() {
		_ = tlsServer.Close()
		_ = redirectServer.Close()
		_ = split.Close()
	})

	return &harness{
		split:  split,
		addr:   listener.Addr().String(),
		port:   port,
		tlsCfg: tlsCfg,
	}
}

// getOverTLS is what a client that was pointed at https does.
func (h *harness) getOverTLS(t *testing.T) string {
	t.Helper()

	client := &http.Client{
		Transport: &http.Transport{
			//nolint:gosec // The certificate is generated by this test and trusted by nobody.
			TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
		},
		Timeout: 5 * time.Second,
	}

	resp, err := client.Get("https://" + h.addr + "/")
	if err != nil {
		t.Fatalf("the request over TLS failed: %v", err)
	}
	defer func() {
		_ = resp.Body.Close()
	}()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		t.Fatalf("reading the answer over TLS: %v", err)
	}

	return string(body)
}

// TestTLSAndPlaintextAreSortedOnTheFirstByte is the split itself: both kinds of
// client reach the same port and each one lands on the server that can answer it.
func TestTLSAndPlaintextAreSortedOnTheFirstByte(t *testing.T) {
	h := newHarness(t)

	if body := h.getOverTLS(t); body != "served over TLS" {
		t.Errorf("the answer over TLS is %q, want the body of the TLS server", body)
	}

	client := &http.Client{
		CheckRedirect: func(*http.Request, []*http.Request) error {
			return http.ErrUseLastResponse
		},
		Timeout: 5 * time.Second,
	}

	resp, err := client.Post("http://"+h.addr+"/api/host?page=2", "application/json",
		strings.NewReader(`{"ip":"192.0.2.10"}`))
	if err != nil {
		t.Fatalf("the request in the clear failed: %v", err)
	}
	defer func() {
		_ = resp.Body.Close()
	}()

	if resp.StatusCode != http.StatusTemporaryRedirect {
		t.Errorf("the request in the clear was answered with %d, want %d",
			resp.StatusCode, http.StatusTemporaryRedirect)
	}

	want := "https://127.0.0.1:" + strconv.Itoa(h.port) + "/api/host?page=2"
	if got := resp.Header.Get("Location"); got != want {
		t.Errorf("Location is %q, want %q", got, want)
	}
}

// TestAConnectionThatSendsNothingDoesNotStopThePort is the failure this design
// exists to avoid. The first byte is what sorts a connection, and a client that
// never sends one would stop the accept loop if it were looked at there,
// leaving every other client of this port unanswered.
func TestAConnectionThatSendsNothingDoesNotStopThePort(t *testing.T) {
	h := newHarness(t)

	silent, err := net.Dial("tcp", h.addr)
	if err != nil {
		t.Fatalf("failed to open the silent connection: %v", err)
	}
	defer func() {
		_ = silent.Close()
	}()

	// Nothing is written on it, on purpose. The requests below run while it is
	// open, which is what the test is about.
	if body := h.getOverTLS(t); body != "served over TLS" {
		t.Errorf("the answer over TLS while a silent connection is open is %q", body)
	}

	client := &http.Client{
		CheckRedirect: func(*http.Request, []*http.Request) error {
			return http.ErrUseLastResponse
		},
		Timeout: 5 * time.Second,
	}

	resp, err := client.Get("http://" + h.addr + "/")
	if err != nil {
		t.Fatalf("the request in the clear while a silent connection is open failed: %v", err)
	}
	_ = resp.Body.Close()

	if resp.StatusCode != http.StatusTemporaryRedirect {
		t.Errorf("the request in the clear was answered with %d, want %d",
			resp.StatusCode, http.StatusTemporaryRedirect)
	}

	// The silent connection is closed once its time is up, so that it does not
	// hold a descriptor for as long as TCP would keep it.
	err = silent.SetReadDeadline(time.Now().Add(5 * time.Second))
	if err != nil {
		t.Fatalf("failed to set the deadline on the silent connection: %v", err)
	}

	_, err = silent.Read(make([]byte, 1))
	if !errors.Is(err, io.EOF) {
		t.Errorf("reading the silent connection gave %v, want it to have been closed", err)
	}
}

// TestTheDeadlineIsClearedAfterTheFirstByte is the mistake this repository made
// once before, in the SSH keepalive: a deadline armed for one read and left on
// the connection ends a later one. Here it would drop a request whose head
// arrives in pieces, and a keep-alive connection a browser holds open between
// requests.
//
// It is read off the connection the splitter hands over rather than through a
// server, because an http.Server sets a read deadline of its own before it
// reads the head and would put the leak right by accident.
func TestTheDeadlineIsClearedAfterTheFirstByte(t *testing.T) {
	listener, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatalf("failed to listen: %v", err)
	}

	split := newSplitter(listener, zap.NewNop(), testPeekTimeout)
	defer func() {
		_ = split.Close()
	}()

	client, err := net.Dial("tcp", listener.Addr().String())
	if err != nil {
		t.Fatalf("failed to connect: %v", err)
	}
	defer func() {
		_ = client.Close()
	}()

	_, err = client.Write([]byte("G"))
	if err != nil {
		t.Fatalf("failed to write the first byte: %v", err)
	}

	accepted, err := split.Plain().Accept()
	if err != nil {
		t.Fatalf("accepting the connection: %v", err)
	}
	defer func() {
		_ = accepted.Close()
	}()

	first := make([]byte, 1)

	_, err = io.ReadFull(accepted, first)
	if err != nil {
		t.Fatalf("reading the first byte back: %v", err)
	}
	if string(first) != "G" {
		t.Fatalf("the first byte read back is %q, want the G that was looked at", first)
	}

	// The rest of the request arrives well after the deadline for the first
	// byte would have fired.
	time.Sleep(3 * testPeekTimeout)

	_, err = client.Write([]byte("ET / HTTP/1.1\r\n"))
	if err != nil {
		t.Fatalf("failed to write the rest of the request: %v", err)
	}

	rest := make([]byte, 3)

	_, err = io.ReadFull(accepted, rest)
	if err != nil {
		t.Fatalf("reading what arrived after the deadline for the first byte: %v. A timeout here "+
			"means the deadline was left on the connection", err)
	}
	if string(rest) != "ET " {
		t.Fatalf("what was read is %q, want the rest of the request line", rest)
	}
}

// TestARequestWhoseHeadArrivesLateIsStillServed is the same thing end to end,
// through the server that answers the plaintext side.
func TestARequestWhoseHeadArrivesLateIsStillServed(t *testing.T) {
	h := newHarness(t)

	conn, err := net.Dial("tcp", h.addr)
	if err != nil {
		t.Fatalf("failed to connect: %v", err)
	}
	defer func() {
		_ = conn.Close()
	}()

	_, err = conn.Write([]byte("G"))
	if err != nil {
		t.Fatalf("failed to write the first byte: %v", err)
	}

	time.Sleep(3 * testPeekTimeout)

	_, err = conn.Write([]byte(fmt.Sprintf("ET /slow HTTP/1.1\r\nHost: %s\r\nConnection: close\r\n\r\n", h.addr)))
	if err != nil {
		t.Fatalf("failed to write the rest of the request: %v", err)
	}

	err = conn.SetReadDeadline(time.Now().Add(5 * time.Second))
	if err != nil {
		t.Fatalf("failed to set the deadline: %v", err)
	}

	answer, err := io.ReadAll(conn)
	if err != nil {
		t.Fatalf("reading the answer: %v", err)
	}

	if !strings.HasPrefix(string(answer), "HTTP/1.1 307") {
		t.Fatalf("the answer is %q, want a redirect", string(answer))
	}
}

// TestClosingTheSplitterClosesThePort covers the shutdown: the socket is let go
// of, so a restart can take the port again, and both sides report that they are
// closed rather than hanging in Accept.
func TestClosingTheSplitterClosesThePort(t *testing.T) {
	h := newHarness(t)

	err := h.split.Close()
	if err != nil {
		t.Fatalf("Close: %v", err)
	}

	_, err = h.split.TLS().Accept()
	if !errors.Is(err, net.ErrClosed) {
		t.Errorf("accepting on the TLS side after the close gave %v, want a closed listener", err)
	}

	_, err = h.split.Plain().Accept()
	if !errors.Is(err, net.ErrClosed) {
		t.Errorf("accepting on the plaintext side after the close gave %v, want a closed listener", err)
	}

	// A second close is what happens for real: the API server closes the
	// listener it was given and the shutdown closes the splitter as well.
	err = h.split.Close()
	if err != nil {
		t.Errorf("the second Close reported %v", err)
	}

	again, err := net.Listen("tcp", h.addr)
	if err != nil {
		t.Fatalf("the port is still held after the close: %v", err)
	}
	_ = again.Close()
}
