name: Go

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - "_scripts/**"
      - "config/**"
      - "test-server/**"
      - ".dockerignore"
      - ".gitignore"
      - "docker-compose.yaml"
      - "Dockerfile"
      - "LICENSE"
      - "**.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Build
      run: make

    - name: Vet
      run: go vet ./...

    - name: Check gofmt
      run: |
        dirs=$(go list -f '{{.Dir}}' ./...)
        unformatted=$(find $dirs -maxdepth 1 -name '*.go' -exec gofmt -l {} +)
        if [ -n "$unformatted" ]; then
          echo "gofmt needed on the following files:"
          echo "$unformatted"
          exit 1
        fi

    - name: Test
      run: go test ./... -count=1 -race
