name: Go

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - ".github/**"
      - "_scripts/**"
      - "config/**"
      - "test-server/**"
      - ".dockerignore"
      - ".gitignore"
      - "docker-compose.yaml"
      - "Dockerfile"
      - "LICENSE"
      - "**.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Build
      run: make
